 @startuml
left to right direction
skinparam packageStyle rectangle

actor "Amine\n(Reader)" as Reader
actor "Sara\n(Contributor)" as Contributor
actor "Ayoub\n(Admin)" as Admin

rectangle "Casa Innov' Blog" {
  usecase "Read Post Details" as UC1
  usecase "Browse Posts" as UC2
  usecase "Add Comment" as UC3
  usecase "Filter Posts\n(by tag)" as UC4
  usecase "Manage Own Posts" as UC5
  usecase "Submit Post" as UC6
  usecase "Manage All Posts\n(Approve/Delete)" as UC7
}


Reader --> UC1
Reader --> UC2
Reader --> UC3
Reader --> UC4

Contributor --> UC5
Contributor --> UC6

Admin --> UC7

UC1 ..> UC2 : <<extend>>
UC4 ..> UC2 : <<extend>>

@enduml